[build-system]
requires = ["setuptools", "wheel", "pybind11", "cibuildwheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hidapi_py"
version = "0.1.0"
authors = [
  { name="Benjamin Heuberger", email="beni.heu@gmail.com" },
]
description = "This package provides a Python wrapper for the hidapi library, allowing for easy access to HID devices."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
[tool.hatch.build]
include = [
  "src/hidapi_py/*.cpp",
  "src/hidapi_py/*.h",
  "src/hidapi_py/__init__.py",
  "CMakeLists.txt",
]

[tool.hatch.build.targets.sdist]
include = ["src/**"]

[project.optional-dependencies]
dev = ["cibuildwheel"]

[project.urls]
Homepage = "https://github.com/Rothen/hidapi-py"
Issues = "https://github.com/Rothen/hidapi-py/issues"