name: Build hidapi-py Windows

on:
  push:
    branches:
      - main

jobs:
  build-win_x64:
    name: Build hidapi-py win_x64
    runs-on: windows-latest
    env:
      CC: clang-cl.exe
      CXX: clang-cl.exe

    defaults:
      run:
        shell: powershell

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ninja
        run: choco install ninja

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 18

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          architecture: "x64"

      - name: Install pip dependencies
        run: |
          pip3 install pybind11-stubgen

      - name: Configure hidapi-py
        run: |
          cmake `
          -S . `
          -B build `
          -G Ninja `
          -DCMAKE_BUILD_TYPE=Release

      - name: Build chiaki-ng
        run: |
          cmake --build build --config Release --clean-first --target hidapi-py

      - name: Upload chiaki-ng Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hidapi-py-win-x64
          path: |
            build/hidapi_py.cp311-win_amd64.pyd
            build/hidapi_py.pyi
            build/hidapi.dll
          if-no-files-found: error
          retention-days: 7