name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        os: [windows-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4

      - name: Set MacOS Env
        if: startsWith(runner.os, 'macOS')
        run: |
          brew install --force hidapi
          echo "CMAKE_ARGS=-DHIDAPI_ROOT=$(brew --prefix hidapi)" >> $GITHUB_ENV

      - name: Set MacOS 13 Env
        if: matrix.os == 'macos-13'
        run: |
          echo "MACOSX_DEPLOYMENT_TARGET=13.0" >> $GITHUB_ENV

      - name: Set MacOS 14 Env
        if: matrix.os == 'macos-14'
        run: |
          echo "MACOSX_DEPLOYMENT_TARGET=14.0" >> $GITHUB_ENV

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.2
        env:
          CIBW_BEFORE_ALL_LINUX: yum -y install hidapi hidapi-devel

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  build-ubuntu_x64:
    name: Build wheels on ubuntu-latest ${{ matrix.python-version }}
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13', '3.14']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: ${{ matrix.python-version }}

      - name: Install apt dependencies
        run: sudo apt install libhidapi-dev

      - name: Install pybind-stubgen
        run: pip3 install pybind11-stubgen

      - name: Build hidapi-py
        run: |
          sudo apt install pipx
          pipx ensurepath
          pipx install build
          pipx run build
          ls dist/

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-ubuntu-latest
          path: ./dist/*.whl