name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.2
        env:
          CIBW_BEFORE_ALL_LINUX: yum -y install hidapi-devel
          CIBW_BEFORE_ALL_MACOS: |
            brew install --force hidapi
            echo "Resolving HIDAPI path..."
            HIDAPI_PREFIX=$(brew --prefix hidapi)
            echo "CMAKE_ARGS=-DHIDAPI_ROOT=$HIDAPI_PREFIX" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl