name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4

      - name: Install Linux dependencies
        if: runner.os == 'ubuntu-latest'
        run: |
          sudo apt install libhidapi-dev

      - name: Install macOS dependencies
        if: runner.os == 'macos-13' || runner.os == 'macos-14'
        run: |
          brew install --force hidapi
          echo "CMAKE_PREFIX_PATH=/opt/homebrew" >> $GITHUB_ENV

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.2

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl